"""Offline, provenance-controlled BioSafe source ingestion contracts."""

from .contracts import (
    ChunkRecord,
    DocumentExtraction,
    ExtractionReport,
    ExtractionStatus,
    PageRecord,
    PreflightReport,
    SourceRecord,
    SourceStatus,
    ValidationError,
)
from .preflight import detect_extraction_backend, load_source_register, run_preflight
from .components import (
    ACTIVATION_PROHIBITED,
    CLAIM_REVIEW_REQUIRED,
    ComponentPolicy,
    ComponentSpan,
    build_component_artifact,
    build_review_ledger,
    load_component_map,
)
from .semantic_fallbacks import (
    FALLBACK_ARTIFACT_VERSION,
    FALLBACK_MAP_VERSION,
    build_semantic_fallback_artifact,
    write_semantic_fallback_artifact,
)
from .fallback_human_review import (
    ALLOWED_DISPOSITIONS,
    HUMAN_REVIEW_COMPLETE,
    HUMAN_REVIEW_REQUIRED,
    REVIEW_MAP_VERSION,
    REVIEW_PACKET_VERSION,
    build_fallback_human_review_packet,
    write_fallback_human_review_packet,
)
from .claim_reconciliation import (
    CLAIM_REVIEW_COMPLETE,
    CROSSWALK_VERSION,
    CURATED_KB_VERSION,
    HUMAN_IDENTITY_REVIEW_COMPLETE,
    HUMAN_IDENTITY_REVIEW_REQUIRED,
    IDENTIFIER_MATCH_VALIDATED,
    RECONCILIATION_MAP_VERSION,
    RECONCILIATION_PACKET_VERSION,
    build_claim_reconciliation_artifacts,
    initialize_claim_reconciliation_map,
    validate_identity_crosswalk,
)
from .claim_review_aid import (
    NO_AUTOMATED_DISPOSITION,
    REVIEW_AID_VERSION,
    build_claim_review_aid,
    write_claim_review_aid,
)
from .legal_claim_review_draft import (
    DRAFT_ARTIFACT_VERSION,
    DRAFT_MAP_VERSION,
    LEGAL_CLAIM_IDS,
    build_legal_claim_review_draft,
    write_legal_claim_review_draft,
)

__all__ = [
    "ChunkRecord",
    "DocumentExtraction",
    "ExtractionReport",
    "ExtractionStatus",
    "PageRecord",
    "PreflightReport",
    "SourceRecord",
    "SourceStatus",
    "ValidationError",
    "ACTIVATION_PROHIBITED",
    "CLAIM_REVIEW_REQUIRED",
    "ComponentPolicy",
    "ComponentSpan",
    "build_component_artifact",
    "build_review_ledger",
    "load_component_map",
    "FALLBACK_ARTIFACT_VERSION",
    "FALLBACK_MAP_VERSION",
    "build_semantic_fallback_artifact",
    "write_semantic_fallback_artifact",
    "ALLOWED_DISPOSITIONS",
    "HUMAN_REVIEW_COMPLETE",
    "HUMAN_REVIEW_REQUIRED",
    "REVIEW_MAP_VERSION",
    "REVIEW_PACKET_VERSION",
    "build_fallback_human_review_packet",
    "write_fallback_human_review_packet",
    "CLAIM_REVIEW_COMPLETE",
    "CROSSWALK_VERSION",
    "CURATED_KB_VERSION",
    "HUMAN_IDENTITY_REVIEW_COMPLETE",
    "HUMAN_IDENTITY_REVIEW_REQUIRED",
    "IDENTIFIER_MATCH_VALIDATED",
    "RECONCILIATION_MAP_VERSION",
    "RECONCILIATION_PACKET_VERSION",
    "build_claim_reconciliation_artifacts",
    "initialize_claim_reconciliation_map",
    "validate_identity_crosswalk",
    "NO_AUTOMATED_DISPOSITION",
    "REVIEW_AID_VERSION",
    "build_claim_review_aid",
    "write_claim_review_aid",
    "DRAFT_ARTIFACT_VERSION",
    "DRAFT_MAP_VERSION",
    "LEGAL_CLAIM_IDS",
    "build_legal_claim_review_draft",
    "write_legal_claim_review_draft",
    "detect_extraction_backend",
    "load_source_register",
    "run_preflight",
]